// PandemicAngular/src/app/component/dispatcher-move/dispatcher-move.component.ts
import { Component, OnInit, Input } from "@angular/core";
import { ModalService } from "src/app/service/modal.service";
import { Client } from "pandemiccommon/dist/out-tsc/";
import { formatPlayer } from "src/app/utils";

@Component({
  selector: "app-dispatcher-move",
  templateUrl: "./dispatcher-move.component.html",
  styleUrls: ["./dispatcher-move.component.styl"],
})
export class DispatcherMoveComponent implements OnInit {
  constructor(private modalService: ModalService) {}

  @Input() other_players: Client.Player[];
  formatPlayer = formatPlayer;
  ngOnInit() {}

  dispatcherMoveTargetSelect(target_player_id: number) {
    this.modalService.dispatcherMoveTarget(target_player_id);
  }

  onCancel() {
    this.modalService.destroyEvent();
  }
}

// pandemic-react/src/move/DispatcherMoveComponent.tsx
import { Client } from "pandemiccommon/dist/out-tsc";
import React from "react";
import { dispatcherMoveTarget } from "../Subscriptions";
import { formatPlayer } from "../utils";

interface DispatcherMoveComponentProps {
  other_players: Client.Player[];
}

export class DispatcherMoveComponent extends React.Component<DispatcherMoveComponentProps> {
  dispatcherMoveTargetSelect(target_player_id: number) {
    dispatcherMoveTarget(target_player_id);
  }

  onCancel() {
    dispatcherMoveTarget();
  }

  render() {
    const { other_players } = this.props;

    return (
      <div>
        <div style={{ marginBottom: "20px" }}>
          {other_players.map((player) => {
            return (
              <button
                key={`dispatcher-choice-${player.id}`}
                onClick={() => this.dispatcherMoveTargetSelect(player.id)}
              >
                Move {formatPlayer(player)}
              </button>
            );
          })}
        </div>
        <div>
          <button onClick={this.onCancel}>Cancel</button>
        </div>
      </div>
    );
  }
}
