// pandemic-react/src/home/HomeComponent.tsx
import { useCallback, useState } from "react";
import { useHistory } from "react-router-dom";

export function HomeComponent() {
  const [matchName, setMatchName] = useState("");
  const history = useHistory();
  const startGame = useCallback(() => history.push(`/game/${matchName}`), [
    history,
  ]);

  return (
    <div id="home-input">
      <h1>"Pandemic Online"</h1>
      Play Pandemic online across multiple devices on a shared board. To create
      a new game or join an existing game, enter a game identifier and click
      'GO'.
      <div>
        <input onChange={(e) => setMatchName(e.target.value)} />
        <button onClick={startGame}>GO</button>
      </div>
    </div>
  );
}

// src/app/component/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.styl']
})
export class HomeComponent implements OnInit {
  match_name: string = ""
  constructor(private router: Router) { }

  ngOnInit() {
  }
  
  startGame() {
    if (this.match_name) {
      this.router.navigate([`/game/${this.match_name}`]);
    } 
  }

}

<div id="home-input">
    Play Pandemic online across multiple devices on a shared board. To create a new game or join an existing game, enter
    a game identifier and click 'GO'.
    <div>
        <input [(ngModel)]="match_name">
        <button (click)="startGame()">GO</button>
    </div>
</div>
