// pandemic-react/src/move-choice-selector/MoveChoiceSelectorComponent.tsx
import { Client } from "pandemiccommon/dist/out-tsc";
import React from "react";

interface MoveChoiceSelectorProps {
  game: Client.Game;
  hand: string[];
  socket: SocketIOClient.Socket;
  canDirect: boolean;
  canCharter: boolean;
  canOperationsExpertMove: boolean;
  currLocation: string;
  targetLocation: string;
  destroy: () => void;
}

interface MoveChoiceSelectorState {
  selectedCard: string;
}

export class MoveChoiceSelectorComponent extends React.Component<
  MoveChoiceSelectorProps,
  MoveChoiceSelectorState
> {
  constructor(props: MoveChoiceSelectorProps) {
    super(props);
    this.state = { selectedCard: "" };
  }

  onDirectFlight() {
    const { socket, targetLocation } = this.props;
    socket.emit("direct flight", targetLocation);
  }

  onCharterFlight() {
    const { socket, targetLocation } = this.props;
    socket.emit("charter flight", targetLocation);
  }

  onOperationsExpertMove() {
    const { socket, targetLocation } = this.props;
    const { selectedCard } = this.state;

    if (selectedCard) {
      socket.emit("operations expert move", targetLocation, selectedCard);
    }
  }

  onCancel() {
    const { destroy } = this.props;
    destroy();
  }

  render() {
    const {
      canDirect,
      canCharter,
      canOperationsExpertMove,
      currLocation,
      targetLocation,
    } = this.props;
    const { selectedCard } = this.state;

    return (
      <div>
        <div style={{ marginBottom: "20px" }}>
          {canDirect && (
            <button onClick={this.onDirectFlight}>
              Direct Flight To {targetLocation} by discarding {targetLocation}
            </button>
          )}
          {canCharter && (
            <button onClick={this.onCharterFlight}>
              Charter Flight To {targetLocation} by discarding {currLocation}
            </button>
          )}
          {canOperationsExpertMove && (
            <button
              disabled={!selectedCard}
              onClick={this.onOperationsExpertMove}
            >
              Operations Expert Move To {targetLocation} by discarding
              {selectedCard ? selectedCard : "a card in your hand"}
            </button>
          )}
        </div>
        {/* TODO Add hand selector
        <div
    *ngIf="canOperationsExpertMove"
    style="display: flex; justify-content: center"
  >
    <app-player-hand
      [hand]="hand"
      [game]="game"
      (onSelect)="onSelectedCard($event)"
      [cardLimit]="hand.length - 1"
    >
    </app-player-hand>
  </div>
        */}
        <div>
          <button onClick={this.onCancel}>Cancel</button>
        </div>
      </div>
    );
  }
}

// PandemicAngular/src/app/component/move-choice-selector/move-choice-selector.component.ts
import { Component, OnInit, Input } from "@angular/core";
import { ModalService } from "src/app/service/modal.service";
import { Client } from "pandemiccommon/dist/out-tsc/";

@Component({
  selector: "app-move-choice-selector",
  templateUrl: "./move-choice-selector.component.html",
  styleUrls: ["./move-choice-selector.component.styl"],
})
export class MoveChoiceSelectorComponent implements OnInit {
  @Input() game: Client.Game;
  @Input() hand: string[];
  @Input() socket: SocketIOClient.Socket;
  @Input() canDirect: boolean;
  @Input() canCharter: boolean;
  @Input() canOperationsExpertMove: boolean;
  @Input() currLocation: string;
  @Input() targetLocation: string;
  selectedCard: string;
  constructor(private modalService: ModalService) {}

  ngOnInit() {}

  onSelectedCard(cardIndex: number) {
    this.selectedCard = this.hand[cardIndex];
  }

  onCancel() {
    this.modalService.destroyEvent();
  }

  onDirectFlight() {
    this.socket.emit("direct flight", this.targetLocation);
  }

  onCharterFlight() {
    this.socket.emit("charter flight", this.targetLocation);
  }

  onOperationsExpertMove() {
    if (this.selectedCard) {
      this.socket.emit(
        "operations expert move",
        this.targetLocation,
        this.selectedCard
      );
    }
  }
}

<div>
  <div style="margin-bottom: 20px">
    <button *ngIf="canDirect" (click)="onDirectFlight()">
      Direct Flight To {{ targetLocation }} by discarding {{ targetLocation }}
    </button>
    <button *ngIf="canCharter" (click)="onCharterFlight()">
      Charter Flight To {{ targetLocation }} by discarding {{ currLocation }}
    </button>
    <button
      *ngIf="canOperationsExpertMove"
      [disabled]="!selectedCard"
      (click)="onOperationsExpertMove()"
    >
      Operations Expert Move To {{ targetLocation }} by discarding
      {{ selectedCard ? selectedCard : "a card in your hand" }}
    </button>
  </div>
  <div
    *ngIf="canOperationsExpertMove"
    style="display: flex; justify-content: center"
  >
    <app-player-hand
      [hand]="hand"
      [game]="game"
      (onSelect)="onSelectedCard($event)"
      [cardLimit]="hand.length - 1"
    >
    </app-player-hand>
  </div>
  <div>
    <button (click)="onCancel()">Cancel</button>
  </div>
</div>
