// PandemicAngular/src/app/start-game/start-game.component.ts
import { Component, Input, OnInit } from "@angular/core";
import { Client } from "pandemiccommon/dist/out-tsc";
import { Subscription } from "rxjs";
import { ModalService } from "../service/modal.service";

@Component({
  selector: "app-start-game",
  templateUrl: "./start-game.component.html",
  styleUrls: ["./start-game.component.styl"],
})
export class StartGameComponent implements OnInit {
  @Input() socket: SocketIOClient.Socket;
  constructor(private modalService: ModalService) {}
  selectedDifficulty: number;
  difficulties = Object.entries(Client.GameDifficultyMap);
  subscription: Subscription;

  ngOnInit(): void {
    this.subscription = this.modalService.start$.subscribe(() => {
      this.modalService.destroy();
    });
  }

  onStart() {
    if (this.selectedDifficulty) {
      this.socket.emit(
        Client.EventName.StartGame,
        this.selectedDifficulty,
        () => {
          console.log(`started game on ${this.selectedDifficulty} succesfully`);
          this.modalService.startAt(
            Client.GameDifficultyMap[this.selectedDifficulty]
          );
        }
      );
    }
  }
}

<button (click)="onStart()">Start Game</button>
<div *ngFor="let difficulty of difficulties" class="difficulties">
  <input
    type="radio"
    [(ngModel)]="selectedDifficulty"
    [value]="difficulty[0]"
  />
  {{ difficulty[1] }}
</div>

// pandemic-react/src/start-game/StartGameComponent.tsx
import { Client } from "pandemiccommon/dist/out-tsc";
import React from "react";
import { destroyEvent } from "../modal/Modal";

const difficulties = Object.entries(Client.GameDifficultyMap);

interface StartGameProps {
  socket: SocketIOClient.Socket;
  destroy: () => void;
}

interface StartGameState {
  selectedDifficulty: number;
}

export class StartGameComponent extends React.Component<
  StartGameProps,
  StartGameState
> {
  constructor(props: StartGameProps) {
    super(props);
    this.onStart = this.onStart.bind(this);
  }

  onStart() {
    const { selectedDifficulty } = this.state;
    const { socket } = this.props;
    if (selectedDifficulty) {
      destroyEvent();
      socket.emit(Client.EventName.StartGame, selectedDifficulty, () => {
        console.log(`started game on ${selectedDifficulty} succesfully`);
      });
    }
  }

  render() {
    return (
      <>
        <button onClick={this.onStart}>Start Game</button>
        {difficulties.map((difficulty) => {
          return (
            <div key={"difficulty" + difficulty} style={{ textAlign: "left" }}>
              <input
                type="radio"
                onChange={(e) =>
                  this.setState({ selectedDifficulty: Number(difficulty[0]) })
                }
              />
              {difficulty[1]}
            </div>
          );
        })}
      </>
    );
  }
}
