// src/app/component/join/join.component.ts
import { Component, OnInit, Input } from "@angular/core";
import { ModalService } from "src/app/service/modal.service";
import { Client } from "data/types";
import { formatPlayer } from "../../utils";

@Component({
  selector: "app-join",
  templateUrl: "./join.component.html",
  styleUrls: ["./join.component.styl"]
})
export class JoinComponent implements OnInit {
  @Input() game: Client.Game;
  @Input() socket: SocketIOClient.Socket;
  @Input() match_name: string;
  @Input() roles: string[];
  formatPlayer = formatPlayer;
  selected_role: string;
  player_name = "";
  constructor(private modalService: ModalService) {}

  ngOnInit() {}

  hasStarted() {
    return this.game && this.game.game_state !== Client.GameState.NotStarted;
  }

  notEnded() {
    return (
      this.game.game_state !== Client.GameState.Lost &&
      this.game.game_state !== Client.GameState.Won
    );
  }

  private joinGameInternal() {
    this.socket.emit(
      "join",
      this.selected_role,
      this.player_name,
      player_index => {
        console.log(
          `${this.player_name} joined as ${this.selected_role} successfully`
        );
        this.modalService.joinAs(
          new PlayerInfo(this.player_name, player_index)
        );
      }
    );
  }

  joinGame() {
    if (this.player_name && this.selected_role) {
      this.joinGameInternal();
    }
  }

  choosePlayer(player: Client.Player) {
    this.player_name = player.name;
    this.selected_role = player.role;
    this.joinGameInternal();
  }
}

export class PlayerInfo {
  player_name: string;
  player_index: number;
  constructor(player_name: string, player_index: number) {
    this.player_name = player_name;
    this.player_index = player_index;
  }
}

<div *ngIf="hasStarted() && notEnded()">
  Join Game as:
  <div *ngFor="let player of game.players">
    <button (click)="choosePlayer(player)">
      {{ formatPlayer(player) }}
    </button>
  </div>
</div>
<div *ngIf="!hasStarted()">
  Join Game as:
  <div>
    <input [(ngModel)]="player_name" />
    <button (click)="joinGame()">JOIN</button>
  </div>
  <div *ngFor="let role of roles">
    <input type="radio" [(ngModel)]="selected_role" [value]="role" /> {{ role }}
  </div>
</div>

// pandemic-react/src/join/Join.tsx
import { Client } from "pandemiccommon/dist/out-tsc";
import React from "react";
import { destroyEvent, joinAs } from "../modal/Modal";
import { formatPlayer, hasStarted } from "../utils";

interface JoinComponentProps {
  game: Client.Game;
  socket: SocketIOClient.Socket;
  roles: Client.Roles[];
}

interface JoinComponentState {
  playerName: string;
  selectedRole: string;
}

export class JoinComponent extends React.Component<
  JoinComponentProps,
  JoinComponentState
> {
  constructor(props: JoinComponentProps) {
    super(props);
    this.state = { playerName: "", selectedRole: "" };
    this.joinGame = this.joinGame.bind(this);
  }

  notEnded() {
    const { game } = this.props;
    return (
      game.game_state !== Client.GameState.Lost &&
      game.game_state !== Client.GameState.Won
    );
  }

  joinGameInternal() {
    const { socket } = this.props;
    const { selectedRole, playerName } = this.state;

    destroyEvent();
    socket.emit(
      Client.EventName.Join,
      selectedRole,
      playerName,
      (player_index: number) => {
        console.log(`${playerName} joined as ${selectedRole} successfully`);
        joinAs(new PlayerInfo(playerName, player_index));
      }
    );
  }

  joinGame() {
    const { selectedRole, playerName } = this.state;
    console.log(selectedRole, playerName);
    if (playerName && selectedRole) {
      this.joinGameInternal();
    }
  }

  choosePlayer(player: Client.Player) {
    this.setState(
      {
        playerName: player.name,
        selectedRole: player.role,
      },
      () => this.joinGameInternal()
    );
  }

  render() {
    const { game, roles } = this.props;

    if (hasStarted(game) && this.notEnded()) {
      return (
        <>
          Join Game as:{" "}
          {game.players.map((player) => {
            return (
              <div key={player.id.toString() + player.name}>
                <button onClick={() => this.choosePlayer(player)}>
                  {formatPlayer(player)}
                </button>
              </div>
            );
          })}
        </>
      );
    } else if (!hasStarted(game)) {
      return (
        <>
          <div>
            <input
              onChange={(e) => this.setState({ playerName: e.target.value })}
            />
            <button onClick={this.joinGame}>JOIN</button>
          </div>
          {roles.map((role) => {
            return (
              <div key={role}>
                <input
                  name="role"
                  type="radio"
                  onChange={(e) => this.setState({ selectedRole: role })}
                />
                {role}
              </div>
            );
          })}
        </>
      );
    } else {
      return null;
    }
  }
}

export class PlayerInfo {
  player_name: string;
  player_index: number;
  constructor(player_name: string, player_index: number) {
    this.player_name = player_name;
    this.player_index = player_index;
  }
}
